title: EDSI - Escuela de Seguridad Industrial
description: Capacitación en seguridad e higiene, lucha contra incendios y primeros auxilios para empresas y particulares.

url: "https://www.edsi.com.ar"
baseurl: ""

lang: es_AR
locale: es_AR

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO plugin settings (opcional pero útil)
author: EDSI

social:
  name: EDSI - Escuela de Seguridad Industrial
  links:
    - https://www.facebook.com/profile.php?id=61585924482145
    - https://www.instagram.com/edsi.ar/
    - https://www.linkedin.com/company/escuela-de-seguridad-industrial/?viewAsMember=true



# Excluir cosas del build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

whatsapp_phone: "5491170616594"
whatsapp_message: "¡Hola!, Vi su *sitio web* y me gustaría hablar con un asesor para obtener mas información de sus servicios."
email: "info@edsi.com.ar"
email_subject: "WEB - Consulta sobre servicios de capacitación"
